# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    pushd '$(projectRoot)'
    pip3 install -r requirements.txt
    python manage.py check
  displayName: 'Run build'


- script: |
    # pushd '$(projectRoot)'
    pip3 install -r requirements.txt
    python manage.py test
  displayName: 'Run tests'

- script: |
    # pushd '$(projectRoot)'
    docker pull hysnsec/bandit
    docker run --user $(id -u):$(id -g) -v $(pwd):/src --rm hysnsec/bandit -r /src -f json -o /src/bandit-output-nofp.json
  # condition: always()
  continueOnError: true
  displayName: 'Run SAST - Bandit'
  
- task: SnykSecurityScan@1
  inputs:
    script: 'pip install -r requirements.txt'
    serviceConnectionEndpoint: 'apare_snyk'
    testType: 'app'
    monitorWhen: 'never'
    # failOnIssues: true
  continueOnError: true


