jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  oast:
    machine: true
    steps:
      - checkout
      
      - run: 
          command: |
              docker run -d -v /django.nv:/src --name safety hysnsec/safety
              docker exec safety check -r /src/requirements.txt --json | tee oast-results.json

      - store_artifacts:
          path: oast-results.json
          destination: safety-artifact

  oast-retire:
    docker:
       - image: node:alpine3.10
    steps:
      - checkout

      - run:
          command: |
              npm install
              npm audit --json | tee retirejs-report2.json
              npm install -g retire
              retire --outputformat json --outputpath retirejs-report.json --severity high

      - store_artifacts:
          path: retirejs-report2.json
          destination: retirejs-artifact

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - oast:
          requires:
            - test
      - oast-retire:
          requires:
            - test
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
